//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_complete.EMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominee
    {
        public int NomineeId { get; set; }
        public string NomineeName { get; set; }
        public Nullable<int> Share_ { get; set; }
        public Nullable<System.DateTime> NomineeDob { get; set; }
        public string NomineeRelation { get; set; }
    }
}
