//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_complete.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaFile
    {
        public int ImageId { get; set; }
        public string Title { get; set; }
        public string ImagePath { get; set; }
        public int Empid { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public short StatusId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
